# Generated by Django 3.2.15 on 2023-01-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_default.jpg', upload_to='users/'),
        ),
    ]
